[2022-07-22 07:36:40,589] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl.merge_data manual__2022-07-22T07:36:37.327113+00:00 [queued]>
[2022-07-22 07:36:40,599] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl.merge_data manual__2022-07-22T07:36:37.327113+00:00 [queued]>
[2022-07-22 07:36:40,601] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 07:36:40,601] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-22 07:36:40,604] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 07:36:40,617] {taskinstance.py:1397} INFO - Executing <Task(_PythonDecoratedOperator): merge_data> on 2022-07-22 07:36:37.327113+00:00
[2022-07-22 07:36:40,624] {standard_task_runner.py:52} INFO - Started process 13077 to run task
[2022-07-22 07:36:40,626] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl', 'merge_data', 'manual__2022-07-22T07:36:37.327113+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_2.py', '--cfg-path', '/tmp/tmpe4h3eryd', '--error-file', '/tmp/tmpsl29r4mm']
[2022-07-22 07:36:40,628] {standard_task_runner.py:80} INFO - Job 46: Subtask merge_data
[2022-07-22 07:36:40,695] {task_command.py:371} INFO - Running <TaskInstance: etl.merge_data manual__2022-07-22T07:36:37.327113+00:00 [running]> on host b51f0a1d5848
[2022-07-22 07:36:40,736] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T07:36:37.327113+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T07:36:37.327113+00:00
[2022-07-22 07:36:40,744] {base.py:68} INFO - Using connection ID 'pg' for task execution.
[2022-07-22 07:36:40,748] {python.py:173} INFO - Done. Returned value was: 1
[2022-07-22 07:36:40,763] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl, task_id=merge_data, execution_date=20220722T073637, start_date=20220722T073640, end_date=20220722T073640
[2022-07-22 07:36:40,802] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 07:36:40,821] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
