[2022-07-21 09:44:56,087] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-21T09:44:51.527598+00:00 [queued]>
[2022-07-21 09:44:56,094] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-21T09:44:51.527598+00:00 [queued]>
[2022-07-21 09:44:56,095] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 09:44:56,096] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-21 09:44:56,096] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 09:44:56,104] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): run_after_loop> on 2022-07-21 09:44:51.527598+00:00
[2022-07-21 09:44:56,109] {standard_task_runner.py:52} INFO - Started process 763 to run task
[2022-07-21 09:44:56,111] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'manual__2022-07-21T09:44:51.527598+00:00', '--job-id', '14', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmplu8876fx', '--error-file', '/tmp/tmp8etibj8e']
[2022-07-21 09:44:56,112] {standard_task_runner.py:80} INFO - Job 14: Subtask run_after_loop
[2022-07-21 09:44:56,157] {task_command.py:371} INFO - Running <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-21T09:44:51.527598+00:00 [running]> on host 29fe348be5eb
[2022-07-21 09:44:56,201] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T09:44:51.527598+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T09:44:51.527598+00:00
[2022-07-21 09:44:56,203] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-21 09:44:56,204] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2022-07-21 09:44:56,211] {subprocess.py:85} INFO - Output:
[2022-07-21 09:44:56,213] {subprocess.py:92} INFO - 1
[2022-07-21 09:44:56,214] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-21 09:44:56,234] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20220721T094451, start_date=20220721T094456, end_date=20220721T094456
[2022-07-21 09:44:56,283] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-21 09:44:56,303] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
